name: Deploy CDK

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    environment: service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install AWS CLI
      run: |
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Enable corepack
      run: |
          npm install -g corepack
          corepack enable

    - name: Install Modules
      run: yarn install --frozen-lockfile

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Generate .env file
      run: |
        echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> .env
        echo "MONGO_DB_NAME=${{ vars.MONGO_DB_NAME }}" >> .env
        echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
        echo "DEEP_SEEK_API_KEY=${{ secrets.DEEP_SEEK_API_KEY }}" >> .env

    - name: Deploy CDK
      run: |
        yarn cdk deploy --require-approval never
