name: Deploy CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install AWS CLI
      run: |
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Enable corepack
      run: |
          npm install -g corepack
          corepack enable

    - name: Install Modules
      run: yarn install --frozen-lockfile

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northeast-2'
